platform :ios, '7.0'
target ‘LuoBoPiaoJu’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'Masonry', '~> 1.0.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJPhotoBrowser', '~> 1.0.2'
pod 'UMengAnalytics'
pod 'XHLogHelper'
pod 'UMengSocialCOM', '~> 5.2.1'
pod 'ReactiveCocoa', '~> 2.5'
end
